# Generated by Django 4.2.16 on 2024-11-29 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Produto',
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['deadline']},
        ),
    ]
