# Generated by Django 4.2.16 on 2024-11-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_todo_produto_alter_produto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='description',
            field=models.CharField(default='temp descr', max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='line',
            field=models.CharField(default='temp line', max_length=50),
        ),
        migrations.AddField(
            model_name='produto',
            name='msrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantity_in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='scale',
            field=models.CharField(default='temp scale', max_length=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='vendor',
            field=models.CharField(default='temp vendor', max_length=50),
        ),
    ]
